/**
 * Short, standard glosses for the 99 Divine Names — keyed by the same
 * `number` field as DIVINE_NAMES in divineNames.ts (1-99, canonical Asmāʾ
 * al-Ḥusnā order). These are the ordinary short renderings found in
 * virtually any reference translation of the 99 Names (e.g. "Al-Ḥamīd —
 * The All-Praiseworthy"), not the interpretive "spiritualInfluence" essays
 * that were deliberately left out of divineNames.ts because the source had
 * no reliable fr/ar text for them. Kept intentionally short (a few words)
 * to stay factual rather than interpretive.
 */

import type { TriText } from './buruj';

export const DIVINE_NAME_MEANING: Record<number, TriText> = {
  1: { en: 'The Most Compassionate', fr: 'Le Tout Miséricordieux', ar: 'الرحيم بجميع خلقه' },
  2: { en: 'The Most Merciful', fr: 'Le Très Miséricordieux', ar: 'الرحيم بالمؤمنين خاصة' },
  3: { en: 'The King, The Sovereign', fr: 'Le Roi, Le Souverain', ar: 'المالك لكل شيء' },
  4: { en: 'The Most Holy, The Pure', fr: 'Le Très Saint, Le Pur', ar: 'المنزّه عن كل نقص' },
  5: { en: 'The Source of Peace', fr: 'La Source de la paix', ar: 'السالم من كل عيب، مصدر السلام' },
  6: { en: 'The Giver of Faith and Security', fr: 'Le Dispensateur de la foi et de la sécurité', ar: 'مانح الأمن والإيمان' },
  7: { en: 'The Guardian, The Protector', fr: 'Le Protecteur vigilant', ar: 'الرقيب الحافظ على خلقه' },
  8: { en: 'The Almighty, The Mighty', fr: 'Le Tout-Puissant', ar: 'العزيز الغالب الذي لا يُغلب' },
  9: { en: 'The Compeller, The Irresistible', fr: "L'Irrésistible", ar: 'الجبّار الذي يقهر خلقه على ما يريد' },
  10: { en: 'The Supreme in Greatness', fr: 'Le Suprêmement Grand', ar: 'المتعالي عن صفات الخلق' },
  11: { en: 'The Creator', fr: 'Le Créateur', ar: 'خالق كل شيء من العدم' },
  12: { en: 'The Evolver, The Maker', fr: 'Celui qui donne forme et existence', ar: 'المُنشئ للخلق على غير مثال' },
  13: { en: 'The Fashioner, The Shaper', fr: 'Celui qui façonne les formes', ar: 'مصوّر الخلق بصورهم المختلفة' },
  14: { en: 'The Ever-Forgiving', fr: 'Celui qui pardonne sans cesse', ar: 'كثير المغفرة لذنوب عباده' },
  15: { en: 'The Subduer, The Dominant', fr: 'Le Dominateur souverain', ar: 'القاهر لكل شيء بقدرته' },
  16: { en: 'The Bestower', fr: 'Le Grand Donateur', ar: 'كثير العطاء بلا مقابل' },
  17: { en: 'The Provider', fr: 'Le Grand Pourvoyeur', ar: 'الرازق لجميع خلقه' },
  18: { en: 'The Opener, The Judge', fr: 'Celui qui ouvre les portes du bien', ar: 'فاتح أبواب الرزق والرحمة' },
  19: { en: 'The All-Knowing', fr: "L'Omniscient", ar: 'العالم بكل شيء ظاهرًا وباطنًا' },
  20: { en: 'The Constrictor, The Withholder', fr: 'Celui qui resserre', ar: 'القابض للرزق والأرواح بحكمته' },
  21: { en: 'The Expander, The Reliever', fr: 'Celui qui étend', ar: 'الباسط للرزق بفضله' },
  22: { en: 'The Abaser, The Humbler', fr: 'Celui qui abaisse', ar: 'خافض من يشاء من العتاة' },
  23: { en: 'The Exalter', fr: 'Celui qui élève', ar: 'رافع من يشاء من عباده' },
  24: { en: 'The Bestower of Honor', fr: 'Celui qui honore', ar: 'معزّ من يشاء من خلقه' },
  25: { en: 'The Humiliator', fr: 'Celui qui humilie', ar: 'مذل من يشاء بعدله' },
  26: { en: 'The All-Hearing', fr: "L'Audient", ar: 'السميع لكل صوت خفي وجلي' },
  27: { en: 'The All-Seeing', fr: 'Le Clairvoyant', ar: 'البصير بكل شيء دقيقه وجليله' },
  28: { en: 'The Judge, The Arbitrator', fr: "L'Arbitre suprême", ar: 'الحاكم الفاصل بين الخلق بالعدل' },
  29: { en: 'The Utterly Just', fr: 'Le Parfaitement Juste', ar: 'العادل الذي لا يجور' },
  30: { en: 'The Subtle, The Gentle', fr: 'Le Subtil, Le Bienveillant', ar: 'اللطيف بعباده في تدبيره' },
  31: { en: 'The All-Aware', fr: 'Celui qui est parfaitement informé', ar: 'الخبير بحقائق الأمور' },
  32: { en: 'The Forbearing, The Clement', fr: 'Le Longanime', ar: 'الحليم الذي لا يعجل بالعقوبة' },
  33: { en: 'The Magnificent, The Supreme', fr: "Le Magnifique, L'Immense", ar: 'العظيم الذي لا أعظم منه' },
  34: { en: 'The All-Forgiving', fr: 'Le Grand Pardonneur', ar: 'الغفور الساتر للذنوب' },
  35: { en: 'The Most Appreciative', fr: 'Celui qui récompense généreusement', ar: 'الشكور الذي يجازي على القليل بالكثير' },
  36: { en: 'The Most High', fr: 'Le Très-Haut', ar: 'العلي الذي لا أعلى منه' },
  37: { en: 'The Greatest, The Most Great', fr: 'Le Très Grand', ar: 'الكبير الذي كل شيء دونه' },
  38: { en: 'The Preserver, The Guardian', fr: 'Le Préservateur', ar: 'الحفيظ الحافظ لكل شيء من الزوال' },
  39: { en: 'The Sustainer, The Nourisher', fr: 'Le Pourvoyeur de subsistance', ar: 'المقيت الذي يوصل القوت لكل مخلوق' },
  40: { en: 'The Reckoner', fr: 'Celui qui tient le compte exact', ar: 'الحسيب الكافي المحاسب لعباده' },
  41: { en: 'The Majestic', fr: 'Le Majestueux', ar: 'الجليل صاحب الجلال والعظمة' },
  42: { en: 'The Most Generous', fr: 'Le Très Généreux', ar: 'الكريم كثير الخير والعطاء' },
  43: { en: 'The Watchful', fr: "L'Observateur vigilant", ar: 'الرقيب المطّلع على كل شيء' },
  44: { en: 'The Responsive, The Answerer', fr: 'Celui qui répond aux invocations', ar: 'المجيب لدعوة من دعاه' },
  45: { en: 'The All-Encompassing, The Vast', fr: "Le Vaste, L'Immense", ar: 'الواسع الذي وسع كل شيء علمًا ورحمة' },
  46: { en: 'The All-Wise', fr: 'Le Sage par excellence', ar: 'الحكيم المصيب في تدبيره' },
  47: { en: 'The Most Loving', fr: 'Le Très Affectueux', ar: 'الودود المحب لأوليائه' },
  48: { en: 'The Glorious, The Magnificent', fr: 'Le Glorieux, Le Magnifique', ar: 'المجيد العظيم الكريم في ذاته وأفعاله' },
  49: { en: 'The Resurrector', fr: 'Celui qui ressuscite', ar: 'الباعث للخلق يوم القيامة' },
  50: { en: 'The Witness', fr: 'Le Témoin', ar: 'الشهيد المطّلع على كل شيء' },
  51: { en: 'The Absolute Truth', fr: 'La Vérité absolue', ar: 'الحق الثابت الذي لا يزول' },
  52: { en: 'The Trustee, The Advocate', fr: 'Le Garant fidèle', ar: 'الوكيل الكافي لمن توكل عليه' },
  53: { en: 'The Most Strong', fr: 'Le Très Fort', ar: 'القوي الذي له القوة كلها' },
  54: { en: 'The Firm, The Steadfast', fr: "Le Ferme, L'Inébranlable", ar: 'المتين شديد القوة' },
  55: { en: 'The Protecting Friend', fr: "L'Ami protecteur", ar: 'الولي الناصر المتولي لأمور المؤمنين' },
  56: { en: 'The All-Praiseworthy', fr: 'Le Digne de louange', ar: 'الحميد المحمود على كل حال' },
  57: { en: 'The Accounter, The Reckoner', fr: 'Celui qui dénombre tout', ar: 'المحصي الذي أحاط علمه بكل شيء عددًا' },
  58: { en: 'The Originator', fr: "L'Initiateur", ar: 'المبدئ الذي أنشأ الخلق ابتداءً' },
  59: { en: 'The Restorer', fr: 'Celui qui restaure', ar: 'المعيد الذي يعيد الخلق بعد الفناء' },
  60: { en: 'The Giver of Life', fr: 'Celui qui donne la vie', ar: 'المحيي واهب الحياة' },
  61: { en: 'The Bringer of Death', fr: 'Celui qui donne la mort', ar: 'المميت الذي يقبض الأرواح' },
  62: { en: 'The Ever-Living', fr: 'Le Vivant éternel', ar: 'الحي الذي لا يموت' },
  63: { en: 'The Self-Subsisting Sustainer', fr: 'Celui qui subsiste par Lui-même', ar: 'القيوم القائم بنفسه المقيم لغيره' },
  64: { en: 'The Perceiver, The Finder', fr: 'Celui qui trouve tout ce qu’Il veut', ar: 'الواجد الغني الذي لا يفتقر' },
  65: { en: 'The All-Noble, The Glorious', fr: 'Le Noble par excellence', ar: 'الماجد العظيم الكريم' },
  66: { en: 'The One', fr: "L'Unique", ar: 'الواحد الذي لا شريك له' },
  67: { en: 'The Only One', fr: 'L’Unique absolu', ar: 'الأحد المتفرد بذاته وصفاته' },
  68: { en: 'The Self-Sufficient Master', fr: 'Le Maître absolu dont tous dépendent', ar: 'الصمد الذي تصمد إليه الخلائق في حوائجها' },
  69: { en: 'The All-Powerful', fr: 'Le Tout-Puissant capable', ar: 'القادر على كل شيء' },
  70: { en: 'The Powerful, The Dominant', fr: 'Celui qui a la pleine maîtrise', ar: 'المقتدر الكامل القدرة' },
  71: { en: 'The Expediter, The Promoter', fr: "Celui qui avance ce qu'Il veut", ar: 'المقدم الذي يقدّم من يشاء' },
  72: { en: 'The Delayer', fr: "Celui qui retarde ce qu'Il veut", ar: 'المؤخر الذي يؤخر من يشاء' },
  73: { en: 'The First', fr: 'Le Premier', ar: 'الأول الذي ليس قبله شيء' },
  74: { en: 'The Last', fr: 'Le Dernier', ar: 'الآخر الذي ليس بعده شيء' },
  75: { en: 'The Manifest, The Evident', fr: "L'Apparent, Le Manifeste", ar: 'الظاهر الذي ظهر فوق كل شيء بقدرته' },
  76: { en: 'The Hidden, The Inward', fr: "Le Caché, L'Intérieur", ar: 'الباطن العالم بما خفي' },
  77: { en: 'The Governor, The Protecting Master', fr: 'Celui qui gouverne toute chose', ar: 'الوالي المتولي لتدبير الخلق' },
  78: { en: 'The Most Exalted', fr: 'Le Très Sublime', ar: 'المتعالي عن كل نقص وشبيه' },
  79: { en: 'The Source of All Goodness', fr: 'Le Bienfaisant', ar: 'البر الرحيم بعباده كثير الإحسان' },
  80: { en: 'The Ever-Relenting', fr: 'Celui qui accueille sans cesse le repentir', ar: 'التواب الذي يقبل توبة عباده' },
  81: { en: 'The Avenger', fr: 'Celui qui se venge des injustes', ar: 'المنتقم من الظالمين بعدله' },
  82: { en: 'The Pardoner', fr: 'Celui qui efface les fautes', ar: 'العفو الذي يمحو الذنوب' },
  83: { en: 'The Most Kind', fr: 'Le Très Bienveillant', ar: 'الرؤوف شديد الرحمة بعباده' },
  84: { en: 'The Owner of All Sovereignty', fr: 'Le Maître de toute royauté', ar: 'مالك الملك المتصرف فيه كيف يشاء' },
  85: { en: 'The Lord of Majesty and Generosity', fr: 'Le Maître de la majesté et de la générosité', ar: 'ذو الجلال والإكرام' },
  86: { en: 'The Equitable', fr: "L'Équitable", ar: 'المقسط الذي يقيم العدل بين خلقه' },
  87: { en: 'The Gatherer', fr: 'Celui qui rassemble', ar: 'الجامع لكل الخلائق يوم القيامة' },
  88: { en: 'The Self-Sufficient, The Rich', fr: 'Le Riche par excellence', ar: 'الغني الذي لا يحتاج إلى أحد' },
  89: { en: 'The Enricher', fr: 'Celui qui enrichit', ar: 'المغني الذي يغني من يشاء من خلقه' },
  90: { en: 'The Preventer', fr: 'Celui qui préserve du mal', ar: 'المانع الذي يمنع ما يشاء عن من يشاء' },
  91: { en: 'The Distresser (by His decree)', fr: 'Celui qui peut nuire par Sa sagesse', ar: 'الضار الذي يقدّر الضر بحكمته' },
  92: { en: 'The Propitious, The Benefactor', fr: 'Celui qui accorde le bien', ar: 'النافع الذي يوصل النفع لمن يشاء' },
  93: { en: 'The Light', fr: 'La Lumière', ar: 'النور الهادي المنير للقلوب والأكوان' },
  94: { en: 'The Guide', fr: 'Le Guide', ar: 'الهادي الذي يرشد إلى الحق' },
  95: { en: 'The Incomparable Originator', fr: 'Celui qui innove sans exemple préalable', ar: 'البديع خالق الأشياء على غير مثال سابق' },
  96: { en: 'The Everlasting', fr: 'L’Éternel qui demeure', ar: 'الباقي الذي لا يفنى' },
  97: { en: 'The Inheritor of All', fr: 'L’Héritier de toute chose', ar: 'الوارث الباقي بعد فناء الخلق' },
  98: { en: 'The Guide to the Right Path', fr: 'Celui qui guide avec sagesse', ar: 'الرشيد الذي يهدي إلى سبيل الرشاد' },
  99: { en: 'The Most Patient', fr: 'Le Très Patient', ar: 'الصبور الذي لا يعاجل العصاة بالعقوبة' },
};
